### ISSUE TITLE
Phase 1 Arrays Lab

### ISSUE THREAD

**Issue by craigjford** [learn-co-curriculum/phase-0-intro-to-js-2-array-lab#11]
### Canvas Link

https://learning.flatironschool.com/courses/4970/assignments/163598?module_item_id=352104

### Concern

I did this Lab during the prework phase.  Is this correct?

**Comment by lizbur10** [comment]
Hi @craigjford ! Yes, there are a number of prework lessons and labs that are repeated in Phase 1 - they cover topics that we feel are particularly important to review. If you are already comfortable with the content in them, you are free to skim or move on. If you would like to redo any of the labs for practice, you will need to delete your current fork of the repo from your GitHub account and fork it again. 💙
