### ISSUE TITLE
precourse work 

### ISSUE THREAD

**Issue by WhatTheFunnn** [learn-co-curriculum/phase-0-intro-to-js-2-array-lab#12]
### Canvas Link

https://learning.flatironschool.com/courses/4970/assignments/163598?module_item_id=352104

### Concern

This was a precourse work lab that is being reused. My code is already preexisting and the lab was done before I entered this part of the module. 

### Suggested Changes

Create a different lab for us to be able to implement our learning please

**Comment by lizbur10** [comment]
Hi @WhatTheFunnn ! There are a number of prework labs that are repeated in Phase 1. (See the "Welcome - What to Expect in Phase 1" lesson for more information.) These labs cover concepts that we feel are particularly important to review. If you are comfortable with the concepts, feel free to skim or move on!

Thanks for contributing to the Flatiron School curriculum 💙

**Comment by WhatTheFunnn** [comment]
I definitely agree with reviewing concepts. But im not particularly as familiar as I would like and was requesting a different lab for practice. Instead of doing one I Already had the answers for.

Dan Souza
________________________________

**Comment by lizbur10** [comment]
Thanks for the feedback! We'll take this suggestion into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
