### ISSUE TITLE
No submit button again

### ISSUE THREAD

**Issue by tfink1975** [learn-co-curriculum/phase-0-intro-to-js-2-array-lab#17]
### Canvas Link

https://learning.flatironschool.com/courses/5290/assignments/165372?module_item_id=356926

### Concern

There is no submit button again for the arrays lab I have paired with a technical coach about it and they said to email admissions and I have not heard back from them just from when I created the issue to pair with a technical coach I am not sure what to do.

**Comment by lizbur10** [comment]
Hi @tfink1975 - have you gotten this resolved? Unfortunately, it's not something we can address from our end - we can fix issues with curriculum materials (content), but this sounds like it may be an issue with your Canvas account. Have you heard back from Admissions?

**Comment by tfink1975** [comment]
No it is still a problem. I have talked to pretty much everybody I can and
I still don’t know what the issue is. I asked admissions and they told me
to ask the technical coaches and they didn’t know what the issue was and
asked me to escalate the problem to admissions so I don’t really know where
to go from here.

Tim Fink

**Comment by lizbur10** [comment]
Sorry to hear that! Let me see if I can escalate this for you 💙

**Comment by tfink1975** [comment]
Yeah I did this and nothing changed.

**Comment by lizbur10** [comment]
Oh good! So glad to hear this has been resolved! I'll go ahead and close this issue 💙
