### ISSUE TITLE
gives wrong command to run test 

### ISSUE THREAD

**Issue by Aaidenplays** [learn-co-curriculum/phase-0-intro-to-js-2-array-lab#26]
In the bottom of the canvas instructions it says

Remember the workflow:
Run the tests using learn test.

learn test does not work. npm test should be the command given. the github readme has the right command but doesnt match what is on canvas

**Comment by lizbur10** [comment]
Hey @Aaidenplays! Can you provide the link to the Canvas page you were looking at? The blueprint is correct so it may just not have synced properly.

**Comment by lizbur10** [comment]
Hi @Aaidenplays - I'm going to go ahead and close this issue. If you find where the problem was, please feel free to reopen it. 💙
