### ISSUE TITLE
Re submit

### ISSUE THREAD

**Issue by Jacoashe** [learn-co-curriculum/phase-0-intro-to-js-2-array-lab#28]
I accidentally pushed before my last edit was done. Can I resubmit or have I failed the lab?

**Comment by lizbur10** [comment]
Hi @Jacoashe ! You can push up code as many times as you need to. Once all the tests are passing, you'll connect to your repo from CodeGrade to submit the assignment. If you've already connected the repo to CodeGrade, all you need to do is push the final code up to GitHub and your submission in CodeGrade will be updated automatically. 💙
