### ISSUE TITLE
Phase 1 Arrays Lab

### ISSUE THREAD

**Issue by fullstackstorm** [learn-co-curriculum/phase-0-intro-to-js-2-array-lab#31]
I am trying to do the phase 1 arrays lab but the link brings me to the already completed: [phase-0-intro-to-js-2-array-lab](https://github.com/learn-co-curriculum/phase-0-intro-to-js-2-array-lab)

**Comment by lizbur10** [comment]
Hi @fullstackstorm ! Sorry for the confusion! Some labs and lessons that we feel are especially important to review appear in Phase 1 as well as Phase 0. You are free to skim over these lessons or skip them entirely if you are comfortable with the content. If you want to redo a lab for practice, you will need to delete your fork of the repo and re-fork it. 

Hope this helps! 💙
