### ISSUE TITLE
Fork Already Exists

### ISSUE THREAD

**Issue by ckelly38** [learn-co-curriculum/phase-0-intro-to-js-2-array-lab#33]
### Canvas Link

https://learning.flatironschool.com/courses/6557/assignments/242757?module_item_id=571160

### Concern

Create a new fork
A fork is a copy of a repository. Forking a repository allows you to freely experiment with changes without affecting the original project.

No more forks can be created. These forks already exist:

(https://github.com/ckelly38/phase-0-intro-to-js-2-array-lab?organization=ckelly38&organization=ckelly38)

### Additional Context

Is the Arrays Lab for Phase 1 the same as the Arrays Lab for Phase 0? If so, that should be NOTED. If not, then wrong github link is posted.

**Comment by lizbur10** [comment]
Hi @ckelly38 - sorry for the confusion! Yes, some of the lessons and labs from Phase 0 are repeated in Phase 1. They cover concepts that we feel are particularly important to understand before moving forward. If you are comfortable with the content in those lessons/labs, you are free to skim or skip them altogether. If you want to re-do any of the labs for practice, you will need to delete your existing fork and fork a fresh copy. 💙
