### ISSUE TITLE
Directs to Phase-0 Assignment

### ISSUE THREAD

**Issue by mborreros** [learn-co-curriculum/phase-0-intro-to-js-2-array-lab#6]
This lab leads to phase-0-intro-to-js-2-array-lab. If this is the lab for this sections and it is a repeat of a previous lab, it would be good to know before beginning the assignment to avoid confusion! Thank you <3

**Comment by ihollander** [comment]
Hi @mborreros, thanks for reaching out! There are a number of lessons that are included in both the prework as well as in Phase 1 that we feel are important for review. This is mentioned in the introduction to Phase 1: https://github.com/learn-co-curriculum/phase-1-welcome-what-to-expect

If you feel comfortable with the content from any of those repeated lessons, you are free to skim or move on.
