### ISSUE TITLE
Wrong forked link? 

### ISSUE THREAD

**Issue by jsltran3** [learn-co-curriculum/phase-0-intro-to-js-2-array-lab#8]
### Canvas Link

https://learning.flatironschool.com/courses/4549/assignments/149816?module_item_id=317811

### Concern

when I fork this assignment, it takes me to the phase-0 lab. Is there supposed to be a phase-1 lab? 

Thanks!

### Suggested Changes

determine if there's a phase-1-arrays lab of sorts

**Comment by lizbur10** [comment]
Hi @jsltran3 ! There are a number of labs in Phase 1 that are repeated from Phase 0. They contain material that is especially important for you to review before you continue in the curriculum. If you are already comfortable with the material being covered, you are free to move on. 

There is additional information and instructions about the repeated labs in the Welcome lesson at the beginning of Phase 1 that you might want to take a look at.
